# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from PySide2 import QtCore, QtGui, QtWidgets
import sys
import random
import time
import glr
from emotion_of_f2 import emotions
from parse import parse_gram, parse_dict, res
from test import diff_files


class Ui_design(object):
    def setupUi(self, design):
        design.setObjectName("design")
        design.resize(1090, 554)
        self.groupBox = QtWidgets.QGroupBox(design)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 741, 521))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 231, 21))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 231, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 40, 231, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(260, 20, 231, 21))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(310, 90, 101, 20))
        self.label.setObjectName("label")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 110, 701, 361))
        self.textEdit_3.setText(
            "Биотехнология – это использование микроорганизмов, биологических систем или биологических процессов в промышленном производстве. В настоящее время при помощи бактерий получают целый ряд веществ: инсулин, гормон роста и др. Человеческий ген встроенный в геном бактерии обеспечивает синтез гормона.")
        self.textEdit_3.setReadOnly(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 470, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 470, 211, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 470, 181, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_6.setGeometry(QtCore.QRect(500, 20, 231, 21))
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 40, 231, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_2 = QtWidgets.QGroupBox(design)
        self.groupBox_2.setGeometry(QtCore.QRect(770, 20, 301, 521))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 171, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 30, 281, 321))
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(80, 360, 141, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 380, 281, 131))
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_3.setDisabled(True)
        self.pushButton_2.clicked.connect(self.load_text)
        self.pushButton.clicked.connect(self.load_lib)
        self.pushButton_3.clicked.connect(self.analyser)
        self.pushButton_4.clicked.connect(self.clear_data)
        self.pushButton_5.clicked.connect(self.reset_data)
        self.pushButton_6.clicked.connect(self.load_f2)
        self.retranslateUi(design)
        QtCore.QMetaObject.connectSlotsByName(design)

    def load_f2(self):
        lib_path = self.getfile()
        f2_name = os.path.basename(lib_path)
        self.textEdit_6.setText(f2_name)
        self.pushButton_6.setText("База знаний загружена")
        self.pushButton_6.setDisabled(True)

        if (self.pushButton_2.isEnabled() == False) and (self.pushButton.isEnabled() == False) and (self.pushButton_6.isEnabled() == False):
            self.pushButton_3.setDisabled(False)
        return f2_name

    def reset_data(self):
        self.textEdit_3.setText(
            "Биотехнология – это использование микроорганизмов, биологических систем или биологических процессов в промышленном производстве. В настоящее время при помощи бактерий получают целый ряд веществ: инсулин, гормон роста и др. Человеческий ген встроенный в геном бактерии обеспечивает синтез гормона.")
        self.pushButton.setText("Загрузить библиотеку")
        self.pushButton_2.setText("Загрузить грамматику")
        self.pushButton_6.setText("Загрузить базу знаний")
        self.pushButton.setDisabled(False)
        self.pushButton_2.setDisabled(False)
        self.pushButton_6.setDisabled(False)
        self.pushButton_3.setDisabled(True)
        self.textEdit.setText("")
        self.textEdit_2.setText("")
        self.textEdit_4.setText("")
        self.textEdit_5.setText("")
        self.textEdit_6.setText("")

    def clear_data(self):
        self.textEdit_3.setText("")

    def retranslateUi(self, design):
        _translate = QtCore.QCoreApplication.translate
        design.setWindowTitle(
            _translate("design", "Метод выделения шаблонов мультимодальной коммуникации в корпусе REC"))
        self.pushButton.setText(_translate("design", "Загрузить библиотеку"))
        self.pushButton_2.setText(_translate("design", "Загрузить грамматику"))
        self.label.setText(_translate("design", "Загружен текст:"))
        self.pushButton_3.setText(_translate("design", "Анализировать текст"))
        self.pushButton_4.setText(_translate("design", "Очистить поле ввода текста"))
        self.pushButton_5.setText(_translate("design", "Сброс параметров"))
        self.pushButton_6.setText(_translate("design", "Загрузить базу знаний"))
        self.label_2.setText(_translate("design", "Результат анализа текста:"))
        self.label_3.setText(_translate("design", "Генерирование BML"))

    def getfile(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(None, "Open " + " Data File", '.', "(*.txt)")[0]
        return fname

    def load_lib(self):
        lib_path = self.getfile()
        lib_name = os.path.basename(lib_path)
        self.textEdit.setText(lib_name)
        self.pushButton.setText("Библиотека загружена")
        self.pushButton.setDisabled(True)
        if (self.pushButton_2.isEnabled() == False) and (self.pushButton.isEnabled() == False) and (self.pushButton_6.isEnabled() == False):
            self.pushButton_3.setDisabled(False)
        return lib_name

    def load_text(self):
        text_path = self.getfile()
        text_name = os.path.basename(text_path)
        self.textEdit_2.setText(text_name)
        self.pushButton_2.setText("Грамматика загружена")
        self.pushButton_2.setDisabled(True)
        if (self.pushButton_2.isEnabled() == False) and (self.pushButton.isEnabled() == False) and (self.pushButton_6.isEnabled() == False):
            self.pushButton_3.setDisabled(False)
        return text_name

    def analyser(self):
        file = open('f2_out.txt', 'wb')
        lib_name = self.textEdit.toPlainText()
        text_name = self.textEdit_2.toPlainText()
        text = self.textEdit_3.toPlainText()
        fname = self.textEdit_6.toPlainText()
        t = time.clock()
        glr = res(text, lib_name, text_name)
        tmp = u''
        for parsed in glr.parse(text):
            tmp += parsed + '\n'
        file.write(tmp.encode('utf-8'))
        self.textEdit_4.setTextColor('black')
        self.textEdit_4.setText(tmp)
        file.close()

        if diff_files(fname) and ("" != self.textEdit_4.toPlainText()):
            self.textEdit_5.setTextColor('green')
            self.textEdit_5.setText(emotions(True))
        else:
            if self.textEdit_4.toPlainText() == '':
                self.textEdit_4.setTextColor('red')
                self.textEdit_4.setText("Ничего не найдено!")
                self.textEdit_5.setTextColor('red')
                self.textEdit_5.setText("Невозможно создать BML-пакет!")
            else:
                self.textEdit_5.setTextColor('red')
                self.textEdit_5.setText(emotions(False))
        print time.clock()-t

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    design = QtWidgets.QWidget()
    ui = Ui_design()
    ui.setupUi(design)
    design.show()
    sys.exit(app.exec_())
